-- One row per person, from first signup through membership.
CREATE TABLE llx_onboarding_applicant(
	rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
	entity integer DEFAULT 1 NOT NULL,
	email varchar(255) NOT NULL,
	firstname varchar(100),
	lastname varchar(100),
	discord varchar(100),
	notify_events integer DEFAULT 0 NOT NULL,
	notify_news integer DEFAULT 0 NOT NULL,
	token_hash varchar(64),
	fk_socpeople integer,
	fk_adherent integer,
	waiver_signed_at datetime,
	waiver_name varchar(200),
	waiver_version varchar(64),
	waiver_ip varchar(64),
	agreement_signed_at datetime,
	agreement_name varchar(200),
	agreement_version varchar(64),
	agreement_ip varchar(64),
	id_uploaded_at datetime,
	id_file varchar(255),
	stage varchar(20) DEFAULT 'details' NOT NULL,
	payment_state varchar(20) DEFAULT 'none' NOT NULL,
	problem_since datetime,
	reminders_sent varchar(255),
	gb_contact_id varchar(64),
	gb_plan_id varchar(64),
	completed_at datetime,
	ip varchar(64),
	datec datetime,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;
